### ISSUE TITLE
Need a Readme

### ISSUE THREAD

**Issue by bluef** [EvilsoulM/Keep_Nice#1]
RT

**Comment by EvilsoulM** [comment]
will fix it soon ....

**Comment by bluef** [comment]
LMFAO

**Comment by EvilsoulM** [comment]
说中文！！！老是说些我不懂的！！！还得我去搜！！！～～～让中文发扬光大！！！

**Comment by EvilsoulM** [comment]
说中文！！！老是说些我不懂的！！！还得我去搜！！！～～～让中文发扬光大！！！@bluef

**Comment by EvilsoulM** [comment]
@bluef 求总经常批评指导 改造！！！

**Comment by bluef** [comment]
@EvilsoulM ...傻逼

**Comment by EvilsoulM** [comment]
@bluef ！！！某创业公司客户端leader公开骂人。。。
